// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTFIfRmgh0SB97U05g5UX-J3YD2bnKcPs',
    appId: '1:726373291721:web:3208af031f1f029ffb1f18',
    messagingSenderId: '726373291721',
    projectId: 'chat-firebase-dio-bb152',
    authDomain: 'chat-firebase-dio-bb152.firebaseapp.com',
    storageBucket: 'chat-firebase-dio-bb152.appspot.com',
    measurementId: 'G-1J0TTW61H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6I2ym2yvMPIlQwiyR_2Cwr9SKeZFGPgc',
    appId: '1:726373291721:android:15d1a880f9f57baffb1f18',
    messagingSenderId: '726373291721',
    projectId: 'chat-firebase-dio-bb152',
    storageBucket: 'chat-firebase-dio-bb152.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ksyzh12qnQNQr_3kctAWMabTKMLDoaw',
    appId: '1:726373291721:ios:aa0fcd3d7409ddbdfb1f18',
    messagingSenderId: '726373291721',
    projectId: 'chat-firebase-dio-bb152',
    storageBucket: 'chat-firebase-dio-bb152.appspot.com',
    iosBundleId: 'com.thiago.firebaseChatDio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ksyzh12qnQNQr_3kctAWMabTKMLDoaw',
    appId: '1:726373291721:ios:aa0fcd3d7409ddbdfb1f18',
    messagingSenderId: '726373291721',
    projectId: 'chat-firebase-dio-bb152',
    storageBucket: 'chat-firebase-dio-bb152.appspot.com',
    iosBundleId: 'com.thiago.firebaseChatDio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTFIfRmgh0SB97U05g5UX-J3YD2bnKcPs',
    appId: '1:726373291721:web:b350efabc3b3970bfb1f18',
    messagingSenderId: '726373291721',
    projectId: 'chat-firebase-dio-bb152',
    authDomain: 'chat-firebase-dio-bb152.firebaseapp.com',
    storageBucket: 'chat-firebase-dio-bb152.appspot.com',
    measurementId: 'G-ESDE6DTWB4',
  );

}